[package]
name = "moonfield-editor"
version.workspace = true
edition.workspace = true

[dependencies]
moonfield-app = { workspace = true }
moonfield-asset = { workspace = true }
moonfield-ecs = { workspace = true }
moonfield-log = { workspace = true }
moonfield-math = { workspace = true }
moonfield-reflect = { workspace = true }
moonfield-render = { workspace = true }
moonfield-renderer = { workspace = true, features = ["splat"] }
moonfield-scene = { workspace = true }
moonfield-window = { workspace = true }
moonfield-winit = { workspace = true }
ash = "0.38.0"
bytemuck = { workspace = true }
gpu-allocator = "0.28.0"
winit = "0.30"
egui = "0.36"
egui-winit = { version = "0.33", default-features = false }
egui_dock = "0.18"
serde_json = { workspace = true }
