[package]
name = "moonfield-renderer"
version.workspace = true
edition.workspace = true

[features]
default = ["splat"]
splat = []
rt = []
gi = []

[dependencies]
moonfield-asset = { workspace = true }
moonfield-math = { workspace = true }
moonfield-render = { workspace = true }
thiserror = { workspace = true }
