[package]
name = "moonfield-renderer"
version.workspace = true
edition.workspace = true

[features]
default = ["splat", "native"]
native = ["moonfield-render/native"]
web = ["moonfield-render/web"]
splat = []
rt = []
gi = []

[dependencies]
moonfield-math = { workspace = true }
moonfield-render = { workspace = true }
thiserror = { workspace = true }
