[package]
name = "moonfield-renderer"
version.workspace = true
edition.workspace = true

[features]
default = ["splat"]
splat = []
rt = []
gi = []

[dependencies]
gltf = { workspace = true }
moonfield-asset = { workspace = true }
moonfield-math = { workspace = true }
moonfield-reflect = { workspace = true }
moonfield-render = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
