[package]
name = "examples"
version = "0.1.0"
edition = "2024"

[dependencies]
moonfield-impl = { path = "../moonfield-impl" }
winit = { workspace = true }

[features]
default = []


[[bin]]
name = "moonfield"
path = "main.rs"
