/// <reference no-default-lib="true"/>
// Auto-generated by moonfield ScriptApi::generate_dts() -- do not edit

declare const console: {
    log(...args: unknown[]): void;
    info(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;
};

declare function record_frame(width?: number, height?: number): void;
