/// <reference no-default-lib="true"/>
// Auto-generated by moonfield ScriptApi::generate_dts() -- do not edit

declare const console: {
    log(...args: unknown[]): void;
    info(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;
};

// Script lifecycle hooks — all optional; missing hooks are skipped.
type MfInputEvent =
    | { type: "key_pressed"; code: string }
    | { type: "key_released"; code: string }
    | { type: "mouse_button_pressed"; button: string }
    | { type: "mouse_button_released"; button: string }
    | { type: "mouse_motion"; dx: number; dy: number }
    | { type: "mouse_wheel"; dx: number; dy: number }
    | { type: "focus_lost" };

type MfWindowEvent =
    | { type: "close_requested" }
    | { type: "resized"; width: number; height: number }
    | { type: "focus_gained" }
    | { type: "focus_lost" };

declare function main(): void;
declare function on_update(dt: number): void;
declare function on_fixed_update(dt: number): void;
declare function on_input(e: MfInputEvent): void;
declare function on_window_event(e: MfWindowEvent): void;
declare function on_shutdown(): void;

declare function record_frame(width?: number, height?: number): void;
declare function input_is_key_pressed(code: string): boolean;
declare function input_is_key_just_pressed(code: string): boolean;
declare function input_is_key_just_released(code: string): boolean;
declare function input_is_mouse_button_pressed(button: string): boolean;
declare function input_is_mouse_button_just_pressed(button: string): boolean;
declare function input_is_mouse_button_just_released(button: string): boolean;
declare function input_mouse_delta(): [number, number];
declare function input_mouse_scroll(): [number, number];
declare function input_is_action_pressed(name: string): boolean;
declare function input_is_action_just_pressed(name: string): boolean;
declare function input_get_axis(negative: string, positive: string): number;
declare function input_get_vector(xNegative: string, xPositive: string, yNegative: string, yPositive: string): [number, number];
declare function input_bind_action(name: string, codes: string[]): void;
declare function app_exit(): void;
declare function app_set_auto_exit_on_close(enabled: boolean): void;
