[package]
name = "moonfield-render"
version.workspace = true
edition.workspace = true

[features]
default = ["native"]
native = [
    "dep:ash",
    "dep:ash-window",
    "dep:gpu-allocator",
    "dep:shader-slang",
    "dep:moonfield-app",
    "dep:moonfield-base",
    "dep:moonfield-ecs",
    "dep:moonfield-log",
    "dep:raw-window-handle",
]
web = ["dep:wgpu"]

[dependencies]
moonfield-app = { workspace = true, optional = true }
moonfield-base = { workspace = true, optional = true }
moonfield-ecs = { workspace = true, optional = true }
moonfield-log = { workspace = true, optional = true }
moonfield-math = { workspace = true }
ash = { version = "0.38.0", optional = true }
ash-window = { version = "0.13.0", optional = true }
bytemuck = { version = "1.23", features = ["derive"] }
gpu-allocator = { version = "0.28.0", optional = true }
raw-window-handle = { version = "0.6.2", optional = true }
shader-slang = { package = "shader-slang-rs", git = "https://github.com/H5uan/shader-slang-rs", optional = true }
wgpu = { version = "30", features = ["spirv"], optional = true }
